# This file is subject to the license agreement located in the file LICENSE
# and cannot be distributed without it. This notice cannot be
# removed or modified.

MAKE := make

ifndef OCR_TYPE
  $(error Need to specify OCR_TYPE!)
endif

include Makefile.$(OCR_TYPE)
